djblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    # Django admin url
    url(r'^admin/', admin.site.urls),


    # URLs fro blogpost app
    url(r'^', include('blogpost.url'))
]

blogpost/models.py
from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template.defaultfilters import slugify
from django.urls import reverse


class BlogSettings(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=50)

    def __str__(self):
        return "Blog settings"


class Post(models.Model):
    title = models.CharField(max_length=50, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=50, unique=True)
    body_preview = models.TextField(default="Preview of post", max_length=200, help_text="Brief overview of post")
    body = models.TextField()
    posted = models.DateTimeField(db_index=True, auto_now_add=True)
    image = models.CharField(max_length=1000)
    NO = 'NO'
    YES = 'YES'
    PINNED = (
        (NO, 'Not pinned'),
        (YES, 'Pinned'),
    )
    pinned = models.CharField(max_length=3, choices=PINNED, default=NO)
    category = models.ForeignKey('blogpost.Category')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogpost:post', args=[self.slug])

    def save(self, *args, **kwargs):
            self.slug = slugify(self.title)
            super(Post, self).save(*args, **kwargs)


class Category(models.Model):
    title = models.CharField(max_length=30, unique=True, db_index=True)
    slug = models.SlugField(max_length=30, unique=True, db_index=True)

    def __str__(self):
        return self.title

    @permalink
    def get_absolute_url(self):
        return 'view_blog_category', None, {'slug': self.slug}

    def save(self, *args, **kwargs):
            self.slug = slugify(self.title)
            super(Category, self).save(*args, **kwargs)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    FOLLOWER = 'FL'
    WRITER = 'WR'
    ADMIN = 'AD'
    USER_GROUP = (
        (FOLLOWER, 'Follower'),
        (WRITER, 'Writer'),
        (ADMIN, 'Admin'),
    )
    user_group = models.CharField(max_length=2, choices=USER_GROUP, default=FOLLOWER)
    username = models.CharField(max_length=30, blank=True)
    slug = models.SlugField(max_length=30, db_index=True)
    avatar = models.CharField(max_length=200)
    facebook = models.CharField(max_length=30, blank=True)
    twitter = models.CharField(max_length=30, blank=True)
    github = models.CharField(max_length=30, blank=True)
    email = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.user.username

    def get_username(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    def save(self, *args, **kwargs):
            self.slug = slugify(self.user.username)
            self.username = self.user.username
            super(Profile, self).save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User)
    posted = models.DateTimeField(db_index=True, auto_now_add=True)
    text = models.TextField(max_length=200)

blogpost/forms.py
from django.contrib.auth.models import User
from .models import Profile, Post, Comment, Category
from django import forms


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        # fields = ['avatar', 'facebook', 'twitter']
        exclude = ['user', 'slug', 'user_group', 'username']


class ProfileAdminForm(forms.ModelForm):

    class Meta:
        model = Profile
        # exclude = ['user', 'slug', 'username']
        fields = ['user_group']


class PostForm(forms.ModelForm):

    # categories = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)

    class Meta:
        model = Post
        # exclude = ['author', 'slug']
        fields = ['title', 'category', 'image', 'body_preview', 'body']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ['user', 'profile', 'post']


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ['title']

blogpost/views.py
from django.views import generic
from .models import Post, Category, BlogSettings, Profile, Comment
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, RedirectView, UpdateView, CreateView
from .forms import UserForm, ProfileForm, PostForm, CommentForm, ProfileAdminForm, CategoryForm
from django.template.defaultfilters import slugify


class PostsView(generic.ListView):
    template_name = 'blogpost/index.html'

    queryset = Post.objects.all().order_by('-posted')

    def get_context_data(self, **kwargs):
        context = super(PostsView, self).get_context_data(**kwargs)
        context['blog'] = BlogSettings.objects.all()[0]
        context['pinned'] = Post.objects.all().get(pinned='YES')
        context['categories'] = Category.objects.all()
        return context


class PostDetailView(View):
    template_name = 'blogpost/post.html'
    form_class = CommentForm

    def get(self, request, slug):
        form = self.form_class(None)
        blog = BlogSettings.objects.all()[0]
        post = Post.objects.get(slug=slug)
        comments = Comment.objects.filter(post=post)
        return render(request, self.template_name, {'blog': blog, 'post': post, 'form': form, 'comments': comments})

    def post(self, request, slug):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            blog_post = Post.objects.filter(slug=slug)[0]
            comment.post = blog_post
            comment.user = request.user
            comment.save()
            return redirect('blogpost:post', slug)


class CategoryDetailView(View):
    template_name = 'blogpost/category.html'

    def get(self, request, slug):
        blog = BlogSettings.objects.all()[0]
        category = get_object_or_404(Category, slug=slug)
        posts = Post.objects.filter(category=category)
        return render(request, self.template_name, {'blog': blog, 'posts': posts})


class UserFormView(View):
    form_class = UserForm
    template_name = 'blogpost/register.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        blog = BlogSettings.objects.all()[0]
        return render(request, self.template_name, {'form': form, 'blog': blog})

    # reg user
    def post(self, request):
        form = self.form_class(request.POST)
        blog = BlogSettings.objects.all()[0]
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blogpost:index')

        return render(request, self.template_name, {'form': form, 'blog': blog})


class LoginView(RedirectView):
    def post(self, request):
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('blogpost:index')
                else:
                    print('Not active')
            else:
                print('No user')
                return redirect('blogpost:index')
        return redirect('blogpost:index')


class LogoutView(RedirectView):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('blogpost:index')


class ProfileView(View):
    model = Profile
    template_name = 'blogpost/profile.html'

    def get(self, request, slug):
        profile = Profile.objects.get(slug=slug)
        blog = BlogSettings.objects.all()[0]
        posts = Post.objects.filter(author=profile.user.pk)
        return render(request, self.template_name, {'blog': blog, 'profile': profile, 'posts': posts})


class ProfileUpdate(View):

    form_class = ProfileForm
    template_name = 'blogpost/profile_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        profile = Profile.objects.get(user=request.user)
        blog = BlogSettings.objects.all()[0]
        return render(request, self.template_name, {'form': form, 'blog': blog, 'initial': profile})

    # update profile
    def post(self, request):
        form = self.form_class(request.POST, instance=request.user.profile)
        slug = slugify(request.user.username)
        if form.is_valid():
            form.save()
            return redirect('blogpost:profile', slug)


class AddPostView(View):
    form_class = PostForm
    template_name = 'blogpost/post_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        blog = BlogSettings.objects.all()[0]
        ctgs = Category.objects.all()
        return render(request, self.template_name, {'form': form, 'blog': blog, 'ctgs': ctgs})

    # add post
    def post(self, request):
        form = PostForm(request.POST)
        if form.is_valid():
            print('Debug: ' + request.POST['title'])
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            slug = post.slug
            return redirect('blogpost:post', slug)
        else:
            print(form.errors)
            print('Debug: ' + request.POST['category'])
            print('DEBUG ' + str(form.is_valid()))
            blog = BlogSettings.objects.all()[0]
            ctgs = Category.objects.all()
            return render(request, self.template_name, {'form': form, 'blog': blog, 'ctgs': ctgs})


class AddCategory(CreateView):
    form_class = CategoryForm
    template_name = 'blogpost/category_form.html'

    def get(self, request):
        form = self.form_class(None)
        blog = BlogSettings.objects.all()[0]
        return render(request, self.template_name, {'form': form, 'blog': blog})

    def post(self, request):
        form = CategoryForm(request.POST)
        if form.is_valid():
            new_ctg = Category(title=request.POST['title'])
            new_ctg.save()
            print('Name:' + request.POST['title'])
            return redirect('blogpost:admin_view')
        else:
            print(form.errors)
            blog = BlogSettings.objects.all()[0]
            return render(request, self.template_name, {'form': form, 'blog': blog})


class UpdatePost(UpdateView):
    model = Post
    template_name = 'blogpost/post_update.html'
    fields = ['title', 'category', 'image', 'body_preview', 'body']

    def get_context_data(self, **kwargs):
        context = super(UpdatePost, self).get_context_data(**kwargs)
        context['blog'] = BlogSettings.objects.all()[0]
        pst_data = Post.objects.get(title=context['post'])
        context['initial'] = pst_data
        context['categories'] = Category.objects.all()
        return context


class CommentDelete(View):

    def post(self, request, slug, pk):
        cmnt = Comment.objects.get(pk=pk)
        cmnt.delete()
        print('debug' + request.path)
        return redirect('blogpost:post', slug)


class PostDelete(View):

    def post(self, request, slug):
        pst = Post.objects.get(slug=slug)
        pst.delete()
        return redirect('blogpost:admin_view')


class AdminView(View):
    template_name = 'blogpost/admin.html'

    def get(self, request):
        blog = BlogSettings.objects.all()[0]
        posts = Post.objects.all()
        profiles = Profile.objects.all()
        comments = Comment.objects.all()
        return render(request, self.template_name, {'blog': blog, 'posts': posts, 'comments': comments,
                                                    'profiles': profiles})


class AdminEditGroup(View):
    form_class = ProfileAdminForm
    template_name = 'blogpost/admin_profile_form.html'

    # display blank form
    def get(self, request, user):
        form = self.form_class(None)
        blog = BlogSettings.objects.all()[0]
        return render(request, self.template_name, {'form': form, 'blog': blog})

    # update profile
    def post(self, request, user):
        usr = Profile.objects.get(username=user)
        form = self.form_class(request.POST, instance=usr)
        if form.is_valid():
            form.save()
            return redirect('blogpost:admin_view')

blogpost/templates/blogpost/admin.html
{% extends "blogpost/base.html" %}
{% block content %}
<div class="container">
{% if user.is_authenticated and user.profile.user_group == 'AD' %}
	<div class="col-lg-12 col-xs-12 col-md-12">
		<div class="col-lg-12 col-xs-12 col-md-12">
			<div class="panel with-nav-tabs panel-default">
				<div class="panel-heading">
					<ul class="nav nav-tabs">
						<li class="active"><a href="#PostsTab" data-toggle="tab">Posts</a></li>
						<li><a href="#CommentsTab" data-toggle="tab">Comments</a></li>
						<li><a href="#ProfilesTab" data-toggle="tab">Profiles</a></li>
					</ul>
				</div>
				<div class="panel-body">
					<div class="tab-content">
						<div class="tab-pane fade in active" id="PostsTab">
							<table class="table table-striped custab">
								<thead>
									<a href="{% url 'blogpost:add_post' %}" class="btn btn-primary pull-right"><b>+</b> Add new post</a>
                                    <a href="{% url 'blogpost:add_category' %}" class="btn btn-primary pull-right"><b>+</b> Add new category</a>
									<tr>
										<th>Title</th>
										<th>Author</th>
                                        <th>Posted</th>
										<th>Category</th>
										<th class="text-center">Preview</th>
										<th class="text-center">Action</th>
									</tr>
								</thead>
								{% for post in posts %}
								<tr>
									<td class="col-md-2"><a href="{% url 'blogpost:post' post.slug %}">{{ post.title }}</a> </td>
									<td class="col-md-1">
                                        <a href="{% url 'blogpost:profile' post.author %}">{{ post.author }}</a>
                                    </td>
                                    <td class="col-md-2">{{ post.posted|date:"d.m.y" }}
                                        {{ post.posted|time:"H:i" }}</td>
									<td class="col-md-1"><a href="{% url 'blogpost:category_view' post.category.slug %}">{{ post.category }}
                                    </a></td>
									<td class="col-md-5">{{ post.body_preview }}</td>
									<td class="text-center col-md-1">
										<a class='btn btn-small btn-success' href="{%  url 'blogpost:update_post' slug=post.slug %}">
										Edit
										</a>
										<form action="{%  url 'blogpost:delete_post' post.slug %}"
											method="POST">
											{% csrf_token %}
											<label>
											<button type="submit" class="btn btn-small btn-danger">
											Del.</button>
											</label>
										</form>
									</td>
								</tr>
								{% endfor %}
							</table>
						</div>
						<div class="tab-pane fade" id="CommentsTab">
							<table class="table table-striped custab">
								<thead>
									<tr>
										<th>Author</th>
                                        <th>Post</th>
										<th>Comment</th>
										<th class="text-center">Action</th>
									</tr>
								</thead>
								{% for comment in comments %}
								<tr>
									<td class="col-md-2">
                                        <a href="{% url 'blogpost:profile' comment.user.username %}">{{ comment.user.username }}</a>
                                    </td>
                                    <td class="col-md-2"><a href="{% url 'blogpost:post' comment.post.slug %}"
                                    >{{ comment.post.title }}</a></td>
									<td class="col-md-7">{{ comment.text }}</td>
									<td class="col-md-1 text-center">
										<form action="
											{%  url 'blogpost:comment_delete' slug=comment.post.slug pk=comment.pk %}"
											method="POST">
											{% csrf_token %}
											<label>
											<button type="submit" class="btn btn-small btn-danger">
											Del.</button>
											</label>
										</form>
									</td>
								</tr>
								{% endfor %}
							</table>
						</div>
						<div class="tab-pane fade" id="ProfilesTab">
							<table class="table table-striped custab">
								<thead>
									<tr>
										<th>Username</th>
										<th>Group</th>
										<th>Email</th>
										<th class="text-center">Action</th>
									</tr>
								</thead>
								{% for profile in profiles %}
								<tr>
									<td class="col-md-1">{{ profile.username }}</td>
									<td class="col-md-2">{{ profile.user_group}}</td>
                                    <td class="col-md-2">{{ profile.email }}</td>
									<td class="col-md-1 text-center">
                                        <a class='btn btn-small btn-success' href="
                                        {%  url 'blogpost:change_group' user=profile.user %}">
										Edit
										</a>
									</td>
								</tr>
								{% endfor %}
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% else %}
    <h3>You should Login or <a href="{% url 'blogpost:register' %}">Signup</a> to view this page</h3>
{% endif %}
</div>
{% endblock %}

blogpost/templates/blogpost/admin_profile_form.html
{% extends "blogpost/base.html" %}
{% block content %}
<div class="container">
{% if user.is_authenticated and user.profile.user_group == 'AD' %}
	<div class="panel panel-default">
        <div class="panel-body registration-panel">
			<div id="legend">
				<legend class="">Change group</legend>
			</div>
			<form class="form-horizontal" action="" method="post"
				enctype="multipart/form-data">
				{%  csrf_token %}
                <!-- TODO -->
			</form>
		</div>
	</div>
{% else %}
    <h3>You should Login or <a href="{% url 'blogpost:register' %}">Signup</a> to view this page</h3>
{% endif %}
</div>
{% endblock content %}

blogpost/templates/blogpost/base.html
{# Load the tag library #}
{% load bootstrap3 %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
{# Bootstrap selector #}
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css" rel="stylesheet">
{# TinyMCE #}
<script src="//cloud.tinymce.com/stable/tinymce.min.js?apiKey=48i7v3kwhg4jefwbpntg5zeqf2ziedn4yw4zsqjsmw874c4c"></script>
<script>tinymce.init({
        selector:'#id_body',
        menubar: false,  // removes the menubar
        plugins: 'image, link, code, preview',
        toolbar: 'bold, italic, underline, aligncenter, quicklink, image, link, code, preview',
    });
</script>
{# Load CSS and JavaScript #}
{% bootstrap_css %}

{# Load static files #}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blogpost/css/style.css' %}" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
<title>{{ blog.title }} - {{ blog.description }}</title>
<!-- header nav -->
<div class="row header vertical-align col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-0 col-xs-offset-0 col-sm-offset-0">
    <div class="menu text-center vertical-center col-lg-2 col-md-2 col-sm-2 col-sx-2">
        <div><a href="#"><i class="fa fa-bars" aria-hidden="true"></i>MENU</a></div>
    </div>
    <div class="logo col-lg-8 col-md-8 col-xs-8 col-sm-8">
        <div>ZEMLETRUS</div>
    </div>
    <div class="login vertical-center text-center col-lg-2 col-md-2 col-sm-2 col-sx-2">
        <a href="#">LOGIN</a>
    </div>
</div>
<!-- Content block -->
<div class="container col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2">
    {% block content %}

    {% endblock %}
</div>

<div class="footer vertical-align col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-0 col-xs-offset-0 col-sm-offset-0">
    <div class="copyright text-center vertical-center col-lg-4 col-md-4 col-sm-4 col-sx-4">
        <div>ZEMLETRUS<i class="fa fa-copyright" aria-hidden="true"></i>2017</div>
    </div>
    <div class="quote col-lg-4 col-md-4 col-xs-4 col-sm-4">
        <div>Who the fuck you think you fuckin' with, I'm the fuckin' boss</div>
    </div>
    <div class="social vertical-center text-center col-lg-4 col-md-4 col-sm-4 col-sx-4">
        Follow us:
        <i class="fa fa-instagram" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-facebook" aria-hidden="true"></i>
        <i class="fa fa-pinterest" aria-hidden="true"></i>
        <i class="fa fa-vk" aria-hidden="true"></i>
    </div>
</div>
<div class="footer-bot text-center vertical-align col-lg-8 col-md-12 col-sm-12 col-xs-12 col-lg-offset-2 col-md-offset-0 col-xs-offset-0 col-sm-offset-0">
    {% for category in categories %}
        <div class="col-lg-3 col-md-3 col-xs-3 col-sm-3">{{ category.title }}</div>
    {%  endfor %}
</div>




{% bootstrap_javascript %}
<script src="{% static 'blogpost/js/app.js' %}"></script>
{% block javascript %}
{% endblock %}

blogpost/templates/blogpost/category_form.html
{% extends "blogpost/base.html" %}
{% block content %}
<div class="container">
{% if user.is_authenticated and user.profile.user_group == 'AD' %}
    <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-10 col-sm-offset-2 col-md-offset-2 col-lg-offset-1">
	<div class="panel panel-default">
        <div class="panel-body registration-panel">
			<div class="panel-heading">
				<h2 class="">Add new category</h2>
			</div>
            <div class="panel-body ">
                <form action="/add_category/" method="post" role="form" >
                    {%  csrf_token %}
                    <div class="form-group">

			    		<label for="id_title">Category name:</label>
                        <input id="id_title" class="form-control " type="text" name="title" value="" placeholder="Name of the new category">
                        <span class="text-danger">{{ form.title.errors.as_text }}</span>
                    </div>

                    <input type="submit" value="Add new category" class="btn btn-info btn-block">

                </form>
            </div>
        </div>
	</div>
    </div>
    </div>
{% else %}
    <h3>You should Login or <a href="{% url 'blogpost:register' %}">Signup</a> to view this page</h3>
{% endif %}
</div>
{% endblock content %}

blogpost/templates/blogpost/post_form.html
{% extends "blogpost/base.html" %}
{% block content %}

<div class="container">
{% if user.is_authenticated and user.profile.user_group != 'FL' %}

	<div class="panel panel-default">
		<div class="panel-body registration-panel">
			<div class="panel-heading">
				<h2 class="">Add new post</h2>
			</div>
			<div class="panel-body ">
				<form class="" action="" method="post"
                    enctype="multipart/form-data">
                    {%  csrf_token %}
					<div class="form-group">
						<label for="id_title">Title:</label>
						<input id="id_title" class="form-control " type="text" name="title" value="" placeholder="Post title...">
                        <span class="text-danger">{{ form.title.errors.as_text }}</span>
                    </div>
					<div class="form-group">
						<label for="id_category">Category:</label>
						<select id="id_category" name="category" class="selectpicker" data-width="100%" required>
                        {% for ctg in ctgs %}
                            <option value="{{ ctg.pk }}">{{ ctg.title }}</option>
                        {% endfor %}

                        </select>
                    </div>
					<div class="form-group">
						<label for="id_image">Image URL:</label>
						<input id="id_image" class="form-control " type="url" name="image" value="" >
                        <span class="text-danger">{{ form.image.errors.as_text }}</span>
                    </div>
                    <div class="form-group">
						<label for="id_body_preview">Post preview text:</label>
						<textarea id="id_body_preview" class="form-control " type="" name="body_preview" placeholder=""></textarea>
                        <span class="text-danger">{{ form.body_preview.errors.as_text }}</span>
                    </div>
					<div class="form-group">
						<label for="id_body">Post text:</label>
						<textarea id="id_body" class="form-control " type="" name="body" placeholder=""></textarea>
                        <span class="text-danger">{{ form.body.errors.as_text }}</span>
					</div>
					<input type="submit" value="Add post" class="btn btn-success col-lg-12 col-md-12 col-sm-12
                    col-xs-12">
							</form>
						</div>
					</div>
				</div>
			</div>
{% elif user.profile.user_group == 'FL' %}

			<h3>Sorry, your user group is
				<u>Follower</u>. You could not add posts.
			</h3>
{% else %}

			<h3>You should Login or
				<a href="{% url 'blogpost:register' %}">Signup</a> to view this page
			</h3>
{% endif %}

		</div>
{% endblock content %}

blogpost/templates/blogpost/post_update.html
{% extends "blogpost/base.html" %}
{% block content %}
<div class="container">
{% if user.is_authenticated and user.profile.user_group != 'FL' %}
	<div class="panel panel-default">
		<div class="panel-body registration-panel">
			<div class="panel-heading">
				<h2 class="">Update post</h2>
			</div>
			<div class="panel-body ">
				<form class="" action="" method="post"
                    enctype="multipart/form-data">
                    {%  csrf_token %}

					<div class="form-group">
						<label for="id_title">Title:</label>
						<input id="id_title" class="form-control " type="text" name="title" value="{{ initial.title }}" placeholder="Post title...">
                        <span class="text-danger">{{ form.title.errors.as_text }}</span>
                    </div>
						<div class="form-group">
							<label for="id_category">Category:</label>
							<select id="id_category" name="category" class="selectpicker" data-width="100%" required>

                                {% for ctg in categories %}
                                    {% if ctg.pk == initial.category.pk %}
                                        <option selected value="{{ initial.category.pk }}">{{ initial.category.title }}</option>
                                    {% else %}
                                        <option value="{{ ctg.pk }}">{{ ctg.title }}</option>
                                    {% endif %}
                                {% endfor %}

							</select>
						</div>
						<div class="form-group">
							<label for="id_image">Image URL:</label>
							<input id="id_image" class="form-control " type="url" name="image" value="
							{{ initial.image }}" >
                            <span class="text-danger">{{ form.image.errors.as_text }}</span>
							</div>
							<div class="form-group">
								<label for="id_body_preview">Post preview text:</label>
								<textarea id="id_body_preview" class="form-control " type="" name="body_preview" placeholder="">{{ initial.body_preview }}</textarea>
							    <span class="text-danger">{{ form.body_preview.errors.as_text }}</span>
                            </div>
							<div class="form-group">
								<label for="id_body">Post text:</label>
								<textarea id="id_body" class="form-control " type="" name="body" placeholder="">{{ initial.body }}</textarea>
							    <span class="text-danger">{{ form.body.errors.as_text }}</span>
                            </div>
							<input type="submit" value="Update post" class="btn btn-success col-lg-12 col-md-12
							col-sm-12
                    col-xs-12">
							</form>
						</div>
					</div>
				</div>
			</div>
{% elif user.profile.user_group == 'FL' %}
    <h3>Sorry, your user group is <u>Follower</u>. You could not update posts.</h3>
{% else %}
    <h3>You should Login or <a href="{% url 'blogpost:register' %}">Signup</a> to view this page</h3>
{% endif %}
</div>
{% endblock content %}

blogpost/templates/blogpost/register.html
{% extends "blogpost/base.html" %}

{% block content %}
<div class="container">
	{% if user.is_authenticated %}
	<h3>Sorry, you already have an account.</h3>
	{% else %}
    <div class="row centered-form">
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-10 col-sm-offset-2 col-md-offset-2 col-lg-offset-1">
	<div class="panel panel-default">
        <div class="panel-body registration-panel">
			<div class="panel-heading">
				<h2 class="">Sign up</h2>
			</div>
            <div class="panel-body ">
			<form class="form-horizontal" action="" method="post"
				enctype="multipart/form-data">
				{%  csrf_token %}
                <div class="form-group">
			    	<label for="id_username">Username:</label>
                    <input id="id_username" class="form-control " type="text" name="username" value="" placeholder="Username">
                </div>
                <div class="form-group">
			    	<label for="id_email">Email:</label>
                    <input id="id_email" class="form-control " type="email" name="email" value="" placeholder="Email">
                </div>
                <div class="form-group">
			    	<label for="id_password">Password:</label>
                    <input id="id_password" class="form-control " type="password" name="password" value="" placeholder="Password">
                </div>
                <div class="form-group">
                    <input type="submit" value="Register" class="btn btn-success col-lg-12 col-md-12 col-sm-12 col-xs-12">
			    </div>
            </form>
            </div>
        </div>
	</div>
    </div>
    </div>
	{% endif %}
</div>
{% endblock content %}